-- Отдельная база для клиентского сервиса (Django).
--
-- База core создаётся самим образом postgres из POSTGRES_DB, а вторую надо завести
-- руками. Разные базы, а не разные схемы, потому что core ведёт схему alembic'ом,
-- а client — миграциями Django: в одной базе они рано или поздно столкнутся на
-- общем пространстве имён таблиц.
--
-- Скрипт выполняется ТОЛЬКО при первой инициализации кластера (пустой том
-- postgres_data). Если база уже поднималась, заведите вручную:
--   docker compose exec postgres psql -U soroka -c "CREATE DATABASE soroka_client;"
CREATE DATABASE soroka_client;
