# Generated by Django 5.2.17 on 2026-08-23 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "core_case_id",
                    models.BigIntegerField(
                        db_index=True, verbose_name="id дела в core"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="активна"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="создана"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "подписка на дело",
                "verbose_name_plural": "подписки на дела",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "core_case_id"),
                        name="uq_subscription_user_case",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PendingCaseSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.CharField(max_length=1000, verbose_name="запрос")),
                (
                    "core_task_id",
                    models.BigIntegerField(verbose_name="id задачи в core"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="создана"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="развязка"
                    ),
                ),
                (
                    "last_error",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="ошибка"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_searches",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "ожидание поиска дела",
                "verbose_name_plural": "ожидания поиска дел",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "core_task_id"), name="uq_pending_user_task"
                    )
                ],
            },
        ),
    ]
