# Generated by Django 5.2.17 on 2026-08-24 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCaseChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "integration_event_id",
                    models.BigIntegerField(verbose_name="id сообщения из core"),
                ),
                (
                    "event_type",
                    models.CharField(max_length=32, verbose_name="тип изменения"),
                ),
                (
                    "core_entity_id",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="id сущности в core"
                    ),
                ),
                ("occurred_at", models.DateTimeField(verbose_name="обнаружено")),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="прочитано"
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changes",
                        to="cases.casesubscription",
                        verbose_name="подписка",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "изменение по делу",
                "verbose_name_plural": "изменения по делам",
                "indexes": [
                    models.Index(
                        condition=models.Q(("read_at__isnull", True)),
                        fields=["subscription"],
                        name="ix_change_unread",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "integration_event_id"),
                        name="uq_change_user_event",
                    )
                ],
            },
        ),
    ]
