# Generated by Django 5.2.17 on 2026-08-24 20:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0002_usercasechange"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="usercasechange",
            name="notified_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="сообщено"),
        ),
        migrations.AddIndex(
            model_name="usercasechange",
            index=models.Index(
                condition=models.Q(("notified_at__isnull", True)),
                fields=["user"],
                name="ix_change_unnotified",
            ),
        ),
    ]
