"""add SearchTask

Revision ID: 1568e40cb4a9
Revises: 19eaec191c93
Create Date: 2026-07-12 14:51:14.745622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1568e40cb4a9'
down_revision: Union[str, Sequence[str], None] = '19eaec191c93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_task',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', name='searchstatus'), nullable=False),
    sa.Column('case_id', sa.BigInteger(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('page_status', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_task_case_id'), 'search_task', ['case_id'], unique=False)
    op.create_index(op.f('ix_search_task_uid'), 'search_task', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_task_uid'), table_name='search_task')
    op.drop_index(op.f('ix_search_task_case_id'), table_name='search_task')
    op.drop_table('search_task')
    # ### end Alembic commands ###
