"""case: add uid, incoming_number; url optional

Revision ID: 19eaec191c93
Revises: 5142f650c54b
Create Date: 2026-07-12 14:32:24.164573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19eaec191c93'
down_revision: Union[str, Sequence[str], None] = '5142f650c54b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case', sa.Column('uid', sa.String(), nullable=False))
    op.add_column('case', sa.Column('incoming_number', sa.String(), nullable=True))
    op.alter_column('case', 'url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_case_uid'), 'case', ['uid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_case_uid'), table_name='case')
    op.alter_column('case', 'url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('case', 'incoming_number')
    op.drop_column('case', 'uid')
    # ### end Alembic commands ###
