"""add case link groups

Revision ID: 5142f650c54b
Revises: c8f1d6f84aac
Create Date: 2026-07-12 13:16:10.393465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5142f650c54b'
down_revision: Union[str, Sequence[str], None] = 'c8f1d6f84aac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_link',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('case', sa.Column('case_link_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_case_case_link_id'), 'case', ['case_link_id'], unique=False)
    op.create_foreign_key(None, 'case', 'case_link', ['case_link_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'case', type_='foreignkey')
    op.drop_index(op.f('ix_case_case_link_id'), table_name='case')
    op.drop_column('case', 'case_link_id')
    op.drop_table('case_link')
    # ### end Alembic commands ###
