"""court add level region code, drop zone parser_type

Revision ID: 71aa569d4757
Revises: 1568e40cb4a9
Create Date: 2026-07-14 00:22:33.183879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71aa569d4757'
down_revision: Union[str, Sequence[str], None] = '1568e40cb4a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Enum-тип уровня суда. Создаём его явно (create_type=False у колонки), иначе
# add_column не создаёт тип автоматически и падает с "type courtlevel does not exist".
courtlevel = sa.Enum('MIRSUD', 'GENERAL', 'APPEAL', 'KAS', name='courtlevel')


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    courtlevel.create(op.get_bind(), checkfirst=True)
    op.add_column('court', sa.Column('code', sa.String(), nullable=False))
    op.add_column('court', sa.Column('level', sa.Enum('MIRSUD', 'GENERAL', 'APPEAL', 'KAS', name='courtlevel', create_type=False), nullable=False))
    op.add_column('court', sa.Column('region', sa.String(), nullable=False))
    op.create_index(op.f('ix_court_code'), 'court', ['code'], unique=True)
    op.drop_column('court', 'parser_type')
    op.drop_column('court', 'zone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('court', sa.Column('zone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('court', sa.Column('parser_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_court_code'), table_name='court')
    op.drop_column('court', 'region')
    op.drop_column('court', 'level')
    op.drop_column('court', 'code')
    # ### end Alembic commands ###
    # Убираем и сам enum-тип, иначе он останется висеть в БД после отката.
    sa.Enum(name='courtlevel').drop(op.get_bind(), checkfirst=True)
