"""initial domain models

Revision ID: c8f1d6f84aac
Revises: 
Create Date: 2026-07-12 13:05:25.074642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8f1d6f84aac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('application_number', sa.String(), nullable=True),
    sa.Column('receipt_date', sa.Date(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_url'), 'case', ['url'], unique=True)
    op.create_table('court',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('zone', sa.String(), nullable=True),
    sa.Column('parser_type', sa.String(), nullable=True),
    sa.Column('base_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('judge',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('side',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('PLAINTIFF', 'DEFENDANT', 'OTHER', name='sidetype'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_court',
    sa.Column('case_id', sa.BigInteger(), nullable=False),
    sa.Column('court_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['court_id'], ['court.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('case_id', 'court_id')
    )
    op.create_table('case_judge',
    sa.Column('case_id', sa.BigInteger(), nullable=False),
    sa.Column('judge_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['judge_id'], ['judge.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('case_id', 'judge_id')
    )
    op.create_table('case_side',
    sa.Column('case_id', sa.BigInteger(), nullable=False),
    sa.Column('side_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['side_id'], ['side.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('case_id', 'side_id')
    )
    op.create_table('court_session',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('case_id', sa.BigInteger(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('place', sa.String(), nullable=True),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('basis', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_court_session_case_id'), 'court_session', ['case_id'], unique=False)
    op.create_table('document',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.BigInteger(), nullable=False),
    sa.Column('document_date', sa.Date(), nullable=True),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('document_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'document_type', 'document_date')
    )
    op.create_index(op.f('ix_document_case_id'), 'document', ['case_id'], unique=False)
    op.create_index(op.f('ix_document_uid'), 'document', ['uid'], unique=True)
    op.create_table('instance',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.BigInteger(), nullable=False),
    sa.Column('instance_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'instance_number')
    )
    op.create_index(op.f('ix_instance_case_id'), 'instance', ['case_id'], unique=False)
    op.create_index(op.f('ix_instance_uid'), 'instance', ['uid'], unique=True)
    op.create_table('place_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.BigInteger(), nullable=False),
    sa.Column('place_date', sa.Date(), nullable=True),
    sa.Column('place_description', sa.Text(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_place_history_case_id'), 'place_history', ['case_id'], unique=False)
    op.create_index(op.f('ix_place_history_uid'), 'place_history', ['uid'], unique=True)
    op.create_table('event',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.BigInteger(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('state_description', sa.Text(), nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_case_id'), 'event', ['case_id'], unique=False)
    op.create_index(op.f('ix_event_uid'), 'event', ['uid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_uid'), table_name='event')
    op.drop_index(op.f('ix_event_case_id'), table_name='event')
    op.drop_table('event')
    op.drop_index(op.f('ix_place_history_uid'), table_name='place_history')
    op.drop_index(op.f('ix_place_history_case_id'), table_name='place_history')
    op.drop_table('place_history')
    op.drop_index(op.f('ix_instance_uid'), table_name='instance')
    op.drop_index(op.f('ix_instance_case_id'), table_name='instance')
    op.drop_table('instance')
    op.drop_index(op.f('ix_document_uid'), table_name='document')
    op.drop_index(op.f('ix_document_case_id'), table_name='document')
    op.drop_table('document')
    op.drop_index(op.f('ix_court_session_case_id'), table_name='court_session')
    op.drop_table('court_session')
    op.drop_table('case_side')
    op.drop_table('case_judge')
    op.drop_table('case_court')
    op.drop_table('side')
    op.drop_table('judge')
    op.drop_table('court')
    op.drop_index(op.f('ix_case_url'), table_name='case')
    op.drop_table('case')
    # ### end Alembic commands ###
