"""case monitoring flag

Флаг регулярного обхода на карточке дела и частичный индекс под выборку планировщика.

Флаг ставит не core: какие дела кому-то интересны, знает клиентский сервис, и он приводит
состояние запросом PUT /monitoring/cases. Core решает лишь, когда обходить помеченные.

server_default false, а не nullable: у существующих карточек колонка должна получить
осмысленное значение сразу, а «неизвестно, обходить ли дело» — не состояние, в котором
может находиться мониторинг.

Индекс частичный: на мониторинге заведомо меньшинство карточек (дела копятся навсегда,
подписки — нет). Колонка в нём last_checked_at, потому что планировщик по ней и
фильтрует, и сортирует — самые давно не проверявшиеся идут первыми.

Revision ID: 40dd61efe7a0
Revises: d91071d0aaae
Create Date: 2026-08-23 17:00:33.298004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40dd61efe7a0'
down_revision: Union[str, Sequence[str], None] = 'd91071d0aaae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case', sa.Column('is_on_monitoring', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_index('ix_case_on_monitoring', 'case', ['last_checked_at'], unique=False, postgresql_where=sa.text('is_on_monitoring'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_case_on_monitoring', table_name='case', postgresql_where=sa.text('is_on_monitoring'))
    op.drop_column('case', 'is_on_monitoring')
    # ### end Alembic commands ###
