"""integration outbox

Очередь сообщений на публикацию наружу: публичный контракт изменений, уезжающий в RabbitMQ.

Вторая таблица рядом с outbox_event, а не колонка published_at в ней. Причина: payload
домен-лога меняется всякий раз, когда парсер начинает отдавать новое поле, а клиентский
сервис от таких правок ломаться не должен. Поэтому наружу уходит отдельное скудное
представление, и колонки здесь — ровно те, что попадают в JSON сообщения.

event_type строкой, а не Enum: иначе переименование внутреннего OutboxEventType требовало
бы миграции публичной таблицы, то есть внутреннее устройство core снова протекло бы в
контракт. Соответствие задано в app/integration_events.py и проверяется тестом.

created_at здесь нет намеренно: occurred_at означает то же самое (момент обнаружения
изменения), и вторая колонка с тем же смыслом только запутала бы.

Revision ID: 83cb47fdcd5a
Revises: 40dd61efe7a0
Create Date: 2026-08-23 22:54:25.494136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83cb47fdcd5a'
down_revision: Union[str, Sequence[str], None] = '40dd61efe7a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_outbox_event',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('case_id', sa.BigInteger(), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=True),
    sa.Column('version', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_outbox_event_case_id'), 'integration_outbox_event', ['case_id'], unique=False)
    op.create_index(op.f('ix_integration_outbox_event_event_type'), 'integration_outbox_event', ['event_type'], unique=False)
    op.create_index('ix_integration_outbox_unpublished', 'integration_outbox_event', ['id'], unique=False, postgresql_where=sa.text('published_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_integration_outbox_unpublished', table_name='integration_outbox_event', postgresql_where=sa.text('published_at IS NULL'))
    op.drop_index(op.f('ix_integration_outbox_event_event_type'), table_name='integration_outbox_event')
    op.drop_index(op.f('ix_integration_outbox_event_case_id'), table_name='integration_outbox_event')
    op.drop_table('integration_outbox_event')
    # ### end Alembic commands ###
