"""initial domain models

Первая и пока единственная ревизия core_v2. Описывает целевое состояние схемы сразу,
одним куском, а не повторяет 27 миграций старого core: у core_v2 своя база
(soroka_core_v2), а alembic_version — однострочная таблица, поэтому две независимые
истории в одной базе невозможны.

Чего здесь нет по сравнению с финальной схемой старого core:

* case.monitoring_enabled  — пользовательский мониторинг живёт не в core;
* таблица instance         — её не заполнял ни парсер, ни задача;
* таблица case_link и case.case_link_id — группы связанных дел не создавал никто;
* document.document_text   — колонка была помечена «намеренно не заполняется»;
* event.document_id        — внешний ключ был, выставлять его никто не выставлял.

Обоснование каждого удаления — services/core_v2_AUDIT.md, раздел 10.

Revision ID: d91071d0aaae
Revises: 
Create Date: 2026-08-22 00:11:02.052880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd91071d0aaae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('court',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('level', sa.Enum('MIRSUD', 'GENERAL', 'APPEAL', 'KAS', name='courtlevel'), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('base_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_court_code'), 'court', ['code'], unique=True)
    op.create_table('judge',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proxy',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('scheme', sa.String(length=16), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('portals', postgresql.ARRAY(sa.String()), server_default=sa.text("'{}'::varchar[]"), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('host', 'port', name='uq_proxy_host_port')
    )
    op.create_index(op.f('ix_proxy_enabled'), 'proxy', ['enabled'], unique=False)
    op.create_index(op.f('ix_proxy_last_used_at'), 'proxy', ['last_used_at'], unique=False)
    op.create_table('side',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('PLAINTIFF', 'DEFENDANT', 'OTHER', name='sidetype'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('court_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('application_number', sa.String(), nullable=True),
    sa.Column('incoming_number', sa.String(), nullable=True),
    sa.Column('receipt_date', sa.Date(), nullable=True),
    sa.Column('registration_date', sa.Date(), nullable=True),
    sa.Column('accepted_date', sa.Date(), nullable=True),
    sa.Column('first_instance_date', sa.Date(), nullable=True),
    sa.Column('first_instance_decision', sa.String(), nullable=True),
    sa.Column('decision_effective_date', sa.Date(), nullable=True),
    sa.Column('superior_case_number', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['court_id'], ['court.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid', 'court_id', 'code', name='uq_case_uid_court_code')
    )
    op.create_index(op.f('ix_case_court_id'), 'case', ['court_id'], unique=False)
    op.create_index(op.f('ix_case_last_checked_at'), 'case', ['last_checked_at'], unique=False)
    op.create_index(op.f('ix_case_uid'), 'case', ['uid'], unique=False)
    op.create_table('case_judge',
    sa.Column('case_id', sa.BigInteger(), nullable=False),
    sa.Column('judge_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['judge_id'], ['judge.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('case_id', 'judge_id')
    )
    op.create_table('case_side',
    sa.Column('case_id', sa.BigInteger(), nullable=False),
    sa.Column('side_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['side_id'], ['side.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('case_id', 'side_id')
    )
    op.create_table('case_url',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('case_id', sa.BigInteger(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_url_case_id'), 'case_url', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_url_url'), 'case_url', ['url'], unique=True)
    op.create_table('court_session',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.BigInteger(), nullable=False),
    sa.Column('session_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('place', sa.String(), nullable=True),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('basis', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_court_session_case_id'), 'court_session', ['case_id'], unique=False)
    op.create_index(op.f('ix_court_session_uid'), 'court_session', ['uid'], unique=True)
    op.create_table('document',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.BigInteger(), nullable=False),
    sa.Column('document_date', sa.Date(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_case_id'), 'document', ['case_id'], unique=False)
    op.create_index(op.f('ix_document_uid'), 'document', ['uid'], unique=True)
    op.create_table('event',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.BigInteger(), nullable=False),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('state_description', sa.Text(), nullable=False),
    sa.Column('document_str', sa.Text(), nullable=True),
    sa.Column('published_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_case_id'), 'event', ['case_id'], unique=False)
    op.create_index(op.f('ix_event_uid'), 'event', ['uid'], unique=True)
    op.create_table('outbox_event',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('case_id', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.Enum('CASE_FIELD_CHANGED', 'EVENT_NEW', 'EVENT_UPDATED', 'EVENT_REMOVED', 'PLACE_NEW', 'PLACE_UPDATED', 'PLACE_REMOVED', 'SESSION_NEW', 'SESSION_UPDATED', 'SESSION_REMOVED', 'DOCUMENT_NEW', 'DOCUMENT_REMOVED', 'JUDGE_ADDED', 'JUDGE_REMOVED', 'SIDE_ADDED', 'SIDE_REMOVED', name='outboxeventtype'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_outbox_event_case_created', 'outbox_event', ['case_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_outbox_event_case_id'), 'outbox_event', ['case_id'], unique=False)
    op.create_index(op.f('ix_outbox_event_created_at'), 'outbox_event', ['created_at'], unique=False)
    op.create_index(op.f('ix_outbox_event_event_type'), 'outbox_event', ['event_type'], unique=False)
    op.create_table('place_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.BigInteger(), nullable=False),
    sa.Column('place_date', sa.Date(), nullable=False),
    sa.Column('place_description', sa.Text(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_place_history_case_id'), 'place_history', ['case_id'], unique=False)
    op.create_index(op.f('ix_place_history_uid'), 'place_history', ['uid'], unique=True)
    op.create_table('search_task',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uid', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', name='searchstatus'), nullable=False),
    sa.Column('case_id', sa.BigInteger(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('page_status', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('uid IS NOT NULL OR source_url IS NOT NULL', name='ck_search_task_uid_or_url'),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_task_case_id'), 'search_task', ['case_id'], unique=False)
    op.create_index(op.f('ix_search_task_source_url'), 'search_task', ['source_url'], unique=False)
    op.create_index(op.f('ix_search_task_uid'), 'search_task', ['uid'], unique=False)
    op.create_table('captcha_solve',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_task_id', sa.BigInteger(), nullable=False),
    sa.Column('search_task_id', sa.BigInteger(), nullable=True),
    sa.Column('case_id', sa.BigInteger(), nullable=True),
    sa.Column('court_id', sa.BigInteger(), nullable=True),
    sa.Column('host', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=5), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('solve_count', sa.Integer(), nullable=True),
    sa.Column('attempt_no', sa.Integer(), nullable=True),
    sa.Column('celery_retry', sa.Integer(), nullable=True),
    sa.Column('captcha_bucket', sa.String(), nullable=True),
    sa.Column('captcha_key', sa.String(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('solved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['court_id'], ['court.id'], ),
    sa.ForeignKeyConstraint(['search_task_id'], ['search_task.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_task_id', name='uq_captcha_solve_provider_task')
    )
    op.create_index(op.f('ix_captcha_solve_case_id'), 'captcha_solve', ['case_id'], unique=False)
    op.create_index(op.f('ix_captcha_solve_court_id'), 'captcha_solve', ['court_id'], unique=False)
    op.create_index(op.f('ix_captcha_solve_created_at'), 'captcha_solve', ['created_at'], unique=False)
    op.create_index(op.f('ix_captcha_solve_search_task_id'), 'captcha_solve', ['search_task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_captcha_solve_search_task_id'), table_name='captcha_solve')
    op.drop_index(op.f('ix_captcha_solve_created_at'), table_name='captcha_solve')
    op.drop_index(op.f('ix_captcha_solve_court_id'), table_name='captcha_solve')
    op.drop_index(op.f('ix_captcha_solve_case_id'), table_name='captcha_solve')
    op.drop_table('captcha_solve')
    op.drop_index(op.f('ix_search_task_uid'), table_name='search_task')
    op.drop_index(op.f('ix_search_task_source_url'), table_name='search_task')
    op.drop_index(op.f('ix_search_task_case_id'), table_name='search_task')
    op.drop_table('search_task')
    op.drop_index(op.f('ix_place_history_uid'), table_name='place_history')
    op.drop_index(op.f('ix_place_history_case_id'), table_name='place_history')
    op.drop_table('place_history')
    op.drop_index(op.f('ix_outbox_event_event_type'), table_name='outbox_event')
    op.drop_index(op.f('ix_outbox_event_created_at'), table_name='outbox_event')
    op.drop_index(op.f('ix_outbox_event_case_id'), table_name='outbox_event')
    op.drop_index('ix_outbox_event_case_created', table_name='outbox_event')
    op.drop_table('outbox_event')
    op.drop_index(op.f('ix_event_uid'), table_name='event')
    op.drop_index(op.f('ix_event_case_id'), table_name='event')
    op.drop_table('event')
    op.drop_index(op.f('ix_document_uid'), table_name='document')
    op.drop_index(op.f('ix_document_case_id'), table_name='document')
    op.drop_table('document')
    op.drop_index(op.f('ix_court_session_uid'), table_name='court_session')
    op.drop_index(op.f('ix_court_session_case_id'), table_name='court_session')
    op.drop_table('court_session')
    op.drop_index(op.f('ix_case_url_url'), table_name='case_url')
    op.drop_index(op.f('ix_case_url_case_id'), table_name='case_url')
    op.drop_table('case_url')
    op.drop_table('case_side')
    op.drop_table('case_judge')
    op.drop_index(op.f('ix_case_uid'), table_name='case')
    op.drop_index(op.f('ix_case_last_checked_at'), table_name='case')
    op.drop_index(op.f('ix_case_court_id'), table_name='case')
    op.drop_table('case')
    op.drop_table('side')
    op.drop_index(op.f('ix_proxy_last_used_at'), table_name='proxy')
    op.drop_index(op.f('ix_proxy_enabled'), table_name='proxy')
    op.drop_table('proxy')
    op.drop_table('judge')
    op.drop_index(op.f('ix_court_code'), table_name='court')
    op.drop_table('court')
    # ### end Alembic commands ###
