# Generated by Django 5.1.4 on 2026-08-08 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoredCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=1000, verbose_name='ссылка на дело')),
                ('state', models.CharField(choices=[('pending', 'ищем дело'), ('active', 'на мониторинге'), ('failed', 'не удалось получить')], default='pending', max_length=16, verbose_name='состояние')),
                ('core_task_id', models.IntegerField(blank=True, null=True, verbose_name='id задачи в core')),
                ('core_case_id', models.IntegerField(blank=True, null=True, verbose_name='id дела в core')),
                ('core_status', models.CharField(blank=True, max_length=255, verbose_name='статус дела')),
                ('core_changed_at', models.DateTimeField(blank=True, null=True, verbose_name='последнее изменение')),
                ('core_last_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='последняя проверка')),
                ('last_error', models.TextField(blank=True, verbose_name='последняя ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='добавлено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitored_cases', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'дело на мониторинге',
                'verbose_name_plural': 'дела на мониторинге',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('user', 'source_url'), name='uq_monitored_user_url'), models.UniqueConstraint(condition=models.Q(('core_case_id__isnull', False)), fields=('user', 'core_case_id'), name='uq_monitored_user_case')],
            },
        ),
    ]
